import os
import streamlit as st

from database.repository import ClaimRepository
from ui.components import metric_card
from ui.theme import page_header
from services.report_service import ReportService

def show_assessment():

    result = st.session_state.get("assessment_result")

    if result is None:
        st.warning("No assessment available.")
        return

    page_header(
        "🤖 AI Damage Assessment",
        "Vehicle damage analysis generated by the AI engine."
    )

    # =====================================================
    # SUMMARY
    # =====================================================

    severity = (
        result.damages[0]["severity"]
        if result.damages
        else "None"
    )

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        metric_card("Claim Status", "Approved")

    with col2:
        metric_card("Severity", severity)

    with col3:
        metric_card(
            "Repair Cost",
            f"₹{result.total_cost:,.0f}"
        )

    with col4:
        metric_card(
            "Fraud Score",
            f"{result.fraud['fraud_score']}%"
        )

    st.divider()

    # =====================================================
    # IMAGES
    # =====================================================

    repo = ClaimRepository()

    try:

        claim_id = st.session_state.get("claim_id")

        images = repo.get_uploaded_images(claim_id)

        left, right = st.columns(2)

        with left:

            st.subheader("📷 Original Image")

            if images:

                image_path = images[0].ImagePath

                if os.path.exists(image_path):

                    st.image(
                        image_path,
                        use_container_width=True,
                    )

                else:

                    st.warning(
                        f"Image not found:\n{image_path}"
                    )

            else:

                st.warning("No uploaded image found.")

        with right:

            st.subheader("🎯 AI Processed Image")

            processed = getattr(
                result,
                "processed_image",
                None,
            )

            if processed is not None:

                st.image(
                    processed,
                    channels="BGR",
                    use_container_width=True,
                )

            else:

                st.info(
                    "Processed image not available."
                )

    finally:

        repo.close()

    st.divider()

   # =====================================================
# DAMAGE DETAILS
# =====================================================

    st.subheader("🚗 Damage Analysis")

    rows = []

    for damage, estimate in zip(result.damages, result.estimates):

        rows.append(
            {
                "Damage ID": damage["damage_id"],
                "Severity": damage["severity"],
                "Area": f"{damage['area']:.0f}",
                "Bounding Box": f"({damage['x']}, {damage['y']})  {damage['width']} × {damage['height']}",
                "Estimated Cost": f"₹{estimate['estimated_cost']:,.0f}",
                "Repair Time": estimate["repair_time"],
            }
        )

    st.dataframe(
        rows,
        use_container_width=True,
        hide_index=True,
    )
    st.divider()

    # =====================================================
    # COST BREAKDOWN
    # =====================================================

    col1, col2 = st.columns(2)

    with col1:

        st.subheader("💰 Cost Breakdown")

        for estimate in result.estimates:

            st.write(
                f"Damage {estimate['damage_id']} : ₹{estimate['estimated_cost']:,.0f}"
            )

        st.divider()

        st.success(
            f"Total Repair Cost : ₹{result.total_cost:,.0f}"
        )

    with col2:

        st.subheader("✅ AI Recommendation")

        fraud = result.fraud["fraud_score"]

        if fraud < 30:
            recommendation = "Approve Claim"
        elif fraud < 70:
            recommendation = "Manual Review"
        else:
            recommendation = "High Fraud Risk"

        st.success(recommendation)

        st.info(f"Fraud Score : {fraud}%")

        if result.estimates:

            repair_days = max(
                estimate["repair_time"]
                for estimate in result.estimates
            )


        else:

            st.warning("No repair estimation available.")

        st.info(f"Estimated Repair Time : {repair_days}")

        st.info("AI Confidence : 95%")

    st.divider()

    # =====================================================
    # ACTIONS
    # =====================================================

    c1, c2, c3 = st.columns(3)

    # --------------------------------------------
    # Save Assessment
    # --------------------------------------------

    with c1:

        if st.button(
            "💾 Save Assessment",
            use_container_width=True,
        ):

            st.success("Assessment already saved.")

    # --------------------------------------------
    # Generate PDF
    # --------------------------------------------

    with c2:

        if st.button(
            "📄 Generate PDF",
            use_container_width=True,
        ):

            try:

                claim_id = st.session_state.get("claim_id")

                filename = f"Claim_Report_{claim_id}.pdf"

                report_service = ReportService()

                report_service.generate_report(
                    filename=filename,
                    claim_id=claim_id,
                    result=result,
                )

                st.success("PDF generated successfully.")

                with open(filename, "rb") as pdf:

                    st.download_button(
                        label="⬇ Download Claim Report",
                        data=pdf,
                        file_name=filename,
                        mime="application/pdf",
                        use_container_width=True,
                    )

            except Exception as ex:

                st.exception(ex)

    # --------------------------------------------
    # New Claim
    # --------------------------------------------

    with c3:

        if st.button(
            "📝 New Claim",
            use_container_width=True,
        ):

            st.session_state["page"] = "claim_form"
            st.rerun()